# Docker
up:
	docker compose -f docker-compose.yml up -d --build

down:
	docker compose -f docker-compose.yml down --remove-orphans

start:
	docker compose -f docker-compose.yml start

stop:
	docker compose -f docker-compose.yml stop

clean:
	docker compose -f docker-compose.yml down -v

logs:
	docker compose -f docker-compose.yml logs -f


