name: vennro

services:
  ansible:
    container_name: ansible-container
    image: vennro-ansible
    build:
      context: ..
      dockerfile: ansible/Dockerfile
    volumes:
      - ../ansible:/ansible
      - ../../config:/config:ro
      - ../../.runtime/ansible:/runtime:ro
      - ~/.ssh:/root/.ssh:ro
    working_dir: /ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    profiles:
      - deploy
