name: vennro

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin-container
    restart: unless-stopped
    volumes:
      - ../phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    networks:
      - proxy

networks:
  proxy:
    external: true
